### ISSUE TITLE
処理や値の内容が分かりやすい名前を付ける

### ISSUE THREAD

**Issue by hellnear7** [ss-mokumoku/osiete-qiita-kun-crawler#1]
以下のメソッド名では何をするメソッドなのか分かりません。
selectするのか、insertするのかといった情報をメソッド名に加えたほうが良いと思います。
https://github.com/ss-mokumoku/osiete-qiita-kun-crawler/blob/8893c932c8883baf02b48002eea51c3053c574a5/db_main.php#L189

引数名についても同様です。
引数に与える値はどのような値なのかが分かる名前にした方が良いと思います。

**Comment by ukyoda** [comment]
併せて、qiita_json_api.php、qiita_json_apiについても関数名と処理の内容が一致していない気がしています。

https://github.com/ss-mokumoku/osiete-qiita-kun-crawler/blob/8893c932c8883baf02b48002eea51c3053c574a5/qiita_json_api.php#L4-L6

あと、ファイル名でdb_main.phpとつけていますが、「main」とかくと、このスクリプトファイルがメインのスクリプト(phpコマンドで実行するスクリプト)かと勘違いしてしまいます。
